/**
 * This schema is used to show the settings form on
 * for the folder of your component
 */
'config' => Array 
(
    'description' => 'Default Configuration Schema', /* This is a topic */
    'fields'      => Array
    ( 
        /* This is the field for the sort order selection. Note, that the description
         * and the widget fields will be translated automatically.
         *
         * Name must match the corresponding configuration key, the domain
         * must match your component.
         *
         * Name of the field and its description is kept as-is, as the clear-text name is
         * set through the l10n database of this component.
         */
    )
),
