'schemadb_config' => 'file:/fi/opengov/datacatalog/config/config_schemadb.inc',
'schemadb_dataset' => 'file:/fi/opengov/datacatalog/config/schemadb_dataset.inc',
'schemadb_info' => 'file:/fi/opengov/datacatalog/config/schemadb_info.inc',
'schemadb_suggestion' => 'file:/fi/opengov/datacatalog/config/schemadb_suggestion.inc',

'use_default_style' => true,

/* icons */
'default_account_icon' => 'stock-icons/16x16/stock_person.png',
'default_new_icon' => 'stock-icons/16x16/list-add.png',
'default_edit_icon' => 'stock-icons/16x16/edit.png',
'default_trash_icon' => 'stock-icons/16x16/trash.png',
'default_list_icon' => 'stock-icons/16x16/text-x-generic-template.png',
'default_hours_icon' => 'stock-icons/16x16/stock_new-event.png',
'default_reports_icon' => 'stock-icons/16x16/stock_new-event.png',

/* allow anonymous suggestions */
'allow_anonymous' => true,
'use_captcha' => true,

/* The captcha widget config to use */
'captcha_config' => Array(),

/* The guid of the topic which holds dataset comments */
'dataset_comments_topic_guid' => '',

/* The id of the topic which holds blog posts */
'blog_topic_id' => '',


