array (
  'mgdschema_class_name' => 'fi_opengov_datacatalog_dataset',
  'midcom_class_name' => 'fi_opengov_datacatalog_dataset_dba',
),
array (
  'mgdschema_class_name' => 'fi_opengov_datacatalog_info',
  'midcom_class_name' => 'fi_opengov_datacatalog_info_dba',
),
array (
  'mgdschema_class_name' => 'fi_opengov_datacatalog_dataset_info',
  'midcom_class_name' => 'fi_opengov_datacatalog_dataset_info_dba',
),
