'organization_type' => array
(
    'description' => 'organization type',
    'fields' => array
    (
        'name' => array
        (
            'title' => 'name',
            'storage' => 'parameter',
            'type' => 'text',
            'widget' => 'text',
            'required' => true,
        ),
        'description' => array
        (
            'title' => 'description',
            'storage' => 'parameter',
            'type' => 'text',
            'widget' => 'text',
            'required' => true,
        ),
    ),
),
